spring:
    profiles:
        active: local
    datasource:
        url: jdbc:h2:tcp://localhost/~/authority
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
#                show_sql: true
                format_sql: true
                user_sql_comment: true
                default_batch_fetch_size: 10

logging.level:
    org:
        hibernate.SQL: debug
#        apache.coyote.http11: debug

server.servlet.session.timeout: 1800
